#!/bin/bash
#
CURRENT_DIR=`pwd`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Process slimmed Delphes -> ROOT from $SCRIPT_DIR"

source $SCRIPT_DIR/setup_lcg.sh

export LD_LIBRARY_PATH=$FASTJET/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./map2rmm/lib/:$LD_LIBRARY_PATH

INPUT=$1
CONFIG=0
OUTPUT="/var/www/html/asc/adfilter/tmp/"

if [ "$#" -eq 2 ]; then
        CONFIG=$2
        echo "Configuration number was set to $CONFIG" 
        echo "Output=$OUTPUT"
fi


if [ "$#" -eq 3 ]; then
        CONFIG=$2
        OUTPUT=$3
        echo "Configuration number was set to $CONFIG" 
        echo "Output directory changed to $OUTPUT"

fi


TMPF=$(basename "${INPUT%.*}")
OUTFILE="$OUTPUT/${TMPF}_rmm.root"

#secondString="_root"
#OUTFILE="${OUTFILE/.root/"$secondString"}"

echo "Input for Map2RMM= $INPUT"
echo "Output from Map2RMM= $OUTFILE"

# Directory with ProMC files from HepSim 
# Make_input data
# echo $INPUT > $SCRIPT_DIR/data.in 

$SCRIPT_DIR/example "$INPUT" "$OUTFILE" $CONFIG

