#!/bin/bash
# set up root
XPWD=`pwd`
echo $XPWD

URRENT_DIR=`pwd`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Process ProMC-> ROOT from $SCRIPT_DIR"

source $SCRIPT_DIR/setup_lcg.sh

echo "Running.."
#make -f Makefile

INPUT=$1
OUTPUT=$2

if [ "$#" -eq 2 ]; then
        CONFIG=$2
        echo "Configuration number was set to $CONFIG"
fi


echo "Input for LHE2PROMC PYTHIA8= $INPUT"

TMPF=$(basename "${INPUT%.*}")
OUTFILE="$OUTPUT/${TMPF}.promc"

echo "Output from LHE2PROMC PYTHIA8= $OUTFILE"

echo "Uncompressing $INPUT"
#fullfile=$INPUT
#filename=$(basename -- "$fullfile")
#extension="${filename##*.}"
#filename="${filename%.*}"
#dir_filename=`dirname -- "$INPUT"`;
#echo $filename
#echo $dir_filename

OUT_LHE="$OUTPUT/${TMPF}"
OUT_PROMC="$OUTPUT/${TMPF}.promc"

echo "Running: gunzip -c $INPUT > $OUT_LHE"
gunzip -c $INPUT > $OUT_LHE  


echo "Running: $SCRIPT_DIR/main.exe cards/tcolor.py $OUT_LHE $OUT_PROMC"
$SCRIPT_DIR/main.exe cards/tcolor.py "$OUT_LHE" "$OUT_PROMC"  | tee logfile.txt

#./main.exe cards/tcolor.py $FF1 Pythia8.promc > logfile.txt

