#!/bin/bash
#
CURRENT_DIR=`pwd`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Process ProMC-> ROOT from $SCRIPT_DIR"

source $SCRIPT_DIR/setup_lcg.sh

export LD_LIBRARY_PATH=$FASTJET/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./map2rmm/lib/:$LD_LIBRARY_PATH

INPUT=$1
CONFIG=0

if [ "$#" -eq 2 ]; then
        CONFIG=$2
    	echo "Configuration number was set to $CONFIG" 
fi

if [ "$#" -ne 2 ]; then
        echo "Configuration number was set to the default $CONFIG"
fi


echo "Input for Map2RMM= $INPUT"
echo "Output from Map2RMM= $INPUT.root"

fullfile=$INPUT
filename=$(basename -- "$fullfile")
extension="${filename##*.}"
filename="${filename%.*}"
dir_filename=`dirname -- "$INPUT"`;

#echo $filename
#echo $dir_filename
OUT_LHE=$dir_filename/$filename
OUT_PROMC=$dir_filename/$filename".promc"

# convert LHE to PROMC
cd $SCRIPT_DIR/package_lhe/
$SCRIPT_DIR/package_lhe/A_RUN_lhe $INPUT 
cd  $SCRIPT_DIR


# Directory with ProMC files from HepSim 
# Make_input data
# echo $INPUT > $SCRIPT_DIR/data.in 

$SCRIPT_DIR/example "$OUT_PROMC" "$INPUT.root" $CONFIG

