#!/bin/bash
#
CURRENT_DIR=`pwd`

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "Process ProMC-> ROOT from $SCRIPT_DIR"

source $SCRIPT_DIR/setup_lcg.sh

export LD_LIBRARY_PATH=$FASTJET/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$SCRIPT_DIR/map2rmm/lib/:$LD_LIBRARY_PATH

INPUT=$1
CONFIG=0
OUTPUT="/var/www/html/asc/adfilter/tmp/"

if [ "$#" -eq 2 ]; then
        CONFIG=$2
        echo "Configuration number was set to $CONFIG" 
        echo "Output=$OUTPUT"
fi


if [ "$#" -eq 3 ]; then
        CONFIG=$2
        OUTPUT=$3
        echo "Configuration number was set to $CONFIG" 
        echo "Output directory changed to $OUTPUT"

fi


echo "Input for Map2RMM= $INPUT"

fullfile=$INPUT
filename=$(basename -- "$fullfile")
extension="${filename##*.}"
filename="${filename%.*}"
dir_filename=$OUTPUT

#echo $filename
#echo $dir_filename
OUT_LHE=$dir_filename/$filename
OUT_PROMC=$dir_filename/$filename".promc"


# convert LHE to PROMC
cd $SCRIPT_DIR/package_lhe/
echo "Running $SCRIPT_DIR/package_lhe/A_RUN_lhe $INPUT $OUTPUT"
$SCRIPT_DIR/package_lhe/A_RUN_lhe $INPUT $OUTPUT 
cd  $SCRIPT_DIR

TMPF=$(basename "${INPUT%.*}")
OUTFILE="$OUTPUT/${TMPF}_rmm.root"

# Directory with ProMC files from HepSim 
# Make_input data
# echo $INPUT > $SCRIPT_DIR/data.in 

echo "Convert ProMC to ROOT"
echo "$SCRIPT_DIR/example $OUT_PROMC $OUTFILE $CONFIG"
$SCRIPT_DIR/example "$OUT_PROMC" $OUTFILE $CONFIG

